### ISSUE TITLE
Unable to train on the Replica_Edge dataset

### ISSUE THREAD

**Issue by C-H-Chien** [cvg/EMAP#7]
Hi! I met an issue when trying to train on the ``Replica_Edge`` dataset. It throws the error message when executing ``bash scripts/run_Replica.bash`` as suggested by README,

(emap) $ bash scripts/run_Replica.bash 
[main.py:77 -                 main() ] Run on scan of room0
Load data: Begin
Load data: End
[main.py:86 -                 main() ] Extracting edges from UDF
[runner_udf.py:514 -         extract_edge() ] Find checkpoint: ckpt_best.pth
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main()
  File "main.py", line 87, in main
    runner.extract_edge(
  File "/EMAP/src/runner/runner_udf.py", line 515, in extract_edge
    self.load_checkpoint(latest_model_name)
  File "/EMAP/src/runner/runner_udf.py", line 253, in load_checkpoint
    checkpoint = torch.load(
  File "/.conda/envs/emap/lib/python3.8/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/.conda/envs/emap/lib/python3.8/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/.conda/envs/emap/lib/python3.8/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './exp/Replica/room0/emap/checkpoints/ckpt_best.pth'

Training on ABC-NEF and DTU_Edge datasets do not have such an issue. Is there something I did wrongly? Thank you!

**Comment by rayeeli** [comment]
Hi, the code for training the UDF field was mistakenly commented out. It should be working now.

**Comment by C-H-Chien** [comment]
Thank you for the updates! That resolves the issue. Closing this thread.
